apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sqlserver
  name: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sqlserver
    spec:
      containers:
      - image: mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04
        name: server
        resources: {}
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: "Testing1122"
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sqlserver       
  name: sqlserver        
spec:
  ports:
  - port: 1433
    protocol: TCP        
    targetPort: 1433     
  selector:
    app: sqlserver       
  type: LoadBalancer     
status:
  loadBalancer: {} 
