apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sqlserver
  name: sqlserver
spec:
  replicas: 20
  selector:
    matchLabels:
      app: sqlserver
  strategy: {}
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - image: mcr.microsoft.com/mssql/server:2025-RTM-ubuntu-22.04
        name: server
        resources: {}
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: "Testing1122"